name: karls
favicon: null
layout_spectrum: 1
typography_spectrum: 0.45585
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.3125
  lightness: 0.07985149882733822
  saturation: 0.5
  rhythmicContrast: 0.44645463139750063
purpose: []
